name: Deploy Extension

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install vsce
        run: npm install -g vsce

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Extension
        run: yarn package

      - name: Publish to VSCode Marketplace
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
